CREATE TABLE IF NOT EXISTS jobs (
    id SERIAL PRIMARY KEY,
    status VARCHAR(30) NOT NULL,
    payload TEXT NOT NULL,
    result TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);