apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy

metadata:
  name: api-gateway-proxy-config
  namespace: job-queue

spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
        externalTrafficPolicy: Cluster
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
                - port: 80
                  nodePort: 30081
                - port: 443
                  nodePort: 30082