apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: aws-secrets
  namespace: job-queue

spec:
  provider: aws

  parameters:
    usePodIdentity: "true"

    objects: |
      - objectName: "job-queue/postgres-secrets"
        objectType: "secretsmanager"
        objectAlias: "postgres-secrets"
        jmesPath:
          - path: POSTGRES_USER
            objectAlias: POSTGRES_USER
          - path: POSTGRES_PASSWORD
            objectAlias: POSTGRES_PASSWORD
          - path: APP_USER
            objectAlias: APP_USER
          - path: APP_PASSWORD
            objectAlias: APP_PASSWORD

  secretObjects:
    - secretName: sms-postgres-credentials-secret
      type: Opaque
      data:
        - objectName: POSTGRES_USER
          key: POSTGRES_USER
        - objectName: POSTGRES_PASSWORD
          key: POSTGRES_PASSWORD
        - objectName: APP_USER
          key: APP_USER
        - objectName: APP_PASSWORD
          key: APP_PASSWORD