apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: configmap-reader
  namespace: job-queue

rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: configmap-reader-binding
  namespace: job-queue

subjects:
  - kind: ServiceAccount
    name: rbac-test
    namespace: job-queue

roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io