apiVersion: v1
kind: ServiceAccount

metadata:
  name: api-service-account
  namespace: job-queue

---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: worker-service-account
  namespace: job-queue

---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: postgres-service-account
  namespace: job-queue

---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: rbac-test 
  namespace: job-queue

