apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy

metadata:
  name: api-gateway-proxy-config
  namespace: job-queue

spec:
  $patch: replace
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Cluster